# Generated by Django 2.1.7 on 2019-05-13 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vod', '0001_initial'),
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_owner_reportcontents', to=settings.AUTH_USER_MODEL, verbose_name='Staff User'),
        ),
        migrations.AddField(
            model_name='report',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_channel_reports', to='vod.Channel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_comment_reports', to='vod.Comment', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='report',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_content_reports', to='service.ReportContent', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_user_reports', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='report',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_video_reports', to='vod.Video', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='reply',
            name='inquiry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_inquiry_reply', to='service.Inquiry', verbose_name='Inquire'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_user_replies', to=settings.AUTH_USER_MODEL, verbose_name='Staff User'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_user_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='helpquestion',
            name='belong_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_belong_to_helpquestions', to='service.HelpQuestion', verbose_name='Belong To'),
        ),
        migrations.AddField(
            model_name='helpquestion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_owner_helpquestions', to=settings.AUTH_USER_MODEL, verbose_name='Staff User'),
        ),
        migrations.AddField(
            model_name='helpanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_question_helpanswer', to='service.HelpQuestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='helpanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_owner_helpanswers', to=settings.AUTH_USER_MODEL, verbose_name='Staff User'),
        ),
    ]
