# Generated by Django 2.1.7 on 2019-05-13 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(None, 'Category'), ('ed', 'Education'), ('tr', 'Travel'), ('ga', 'Game'), ('sh', 'Shopping'), ('fi', 'Fitness')], max_length=2, verbose_name='Category')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('background_image', models.ImageField(blank=True, upload_to='background_image/%Y/%m/%d', verbose_name='Background Image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Channel Create Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vod_owner_channels', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Content')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vod_reply_comments', to='vod.Comment', verbose_name='Reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vod_user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('video', models.FileField(blank=True, upload_to='video/%Y/%m/%d', verbose_name='Video')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vod_channel_videos', to='vod.Channel', verbose_name='Channel')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-update_date'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vod_video_comments', to='vod.Video', verbose_name='Video'),
        ),
    ]
