# Generated by Django 2.1.7 on 2019-05-13 17:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.+-]+$', 'Enter a valid username.', 'invalid')], verbose_name='Id')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[(None, 'Gender'), ('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='Gender')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image/%Y/%m/%d', verbose_name='Profile image')),
                ('address1', models.CharField(blank=True, help_text='Street address, P.O box, company name, c/o', max_length=100, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor', max_length=100, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('state_province_region', models.CharField(blank=True, max_length=50, verbose_name='State/Province/Region')),
                ('zip', models.CharField(blank=True, max_length=20, verbose_name='ZIP')),
                ('city_region', models.CharField(blank=True, max_length=50, verbose_name='City/Region')),
                ('bank_name', models.CharField(blank=True, max_length=30, verbose_name='Bank Name')),
                ('account_holder', models.CharField(blank=True, max_length=180, verbose_name='Account Holder')),
                ('account_number', models.CharField(blank=True, max_length=30, verbose_name='Account Number')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Join')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['date_joined'],
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Subscribe Create Date')),
                ('subscribe_expire_date', models.DateTimeField(blank=True, verbose_name='Subscribe Expire Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_subscribe', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Subscribe',
                'verbose_name_plural': 'Subscribes',
                'ordering': ['subscribe_expire_date'],
            },
        ),
    ]
