# Generated by Django 2.1.7 on 2019-05-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vod', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_comments',
            field=models.ManyToManyField(blank=True, related_name='user_like_comments_users', to='vod.Comment', verbose_name='Like Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_videos',
            field=models.ManyToManyField(blank=True, related_name='user_like_videos_users', to='vod.Video', verbose_name='Like Video'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_channels',
            field=models.ManyToManyField(blank=True, related_name='user_subscribe_channels_users', to='vod.Channel', verbose_name='Subscribe Channel'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
